spring.application.name=E-CommerceAPI
spring.datasource.url=jdbc:mysql://localhost:3306/EcommerceDB
spring.datasource.username=root
spring.datasource.password=ArjunBadoni@12
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt_secret=thisismysupersecretkeyforthisjwtbasedauthentication
